"""Seed UniFlow colleges, departments, admins, faculty, and students.

Uses PostgreSQL schema reflection so the script never creates or alters tables.
Set DATABASE_URL to override the local connection settings. Set
SEED_PASSWORD_HASH to a hash generated by the application's password hasher;
the default marker is intentionally not a usable password hash.
"""

import os
import sys
import uuid

try:
    from sqlalchemy import MetaData, create_engine, select
    from sqlalchemy.exc import SQLAlchemyError
except ImportError as exc:
    print(
        "SQLAlchemy is required to seed the database. Install SQLAlchemy and a "
        "PostgreSQL driver in the active Python environment.",
        file=sys.stderr,
    )
    raise SystemExit(1) from exc


DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://uniflow_admin:uniflow_secure_pass123@localhost:5432/uniflow_db",
)
PASSWORD_HASH = os.getenv("SEED_PASSWORD_HASH", "!seeded-account-no-login!")

COLLEGES = (
    {
        "name": "Northstar State University",
        "slug": "northstar-state",
        "domain": "northstar.example.edu",
    },
    {
        "name": "Lakeside Polytechnic Institute",
        "slug": "lakeside-polytechnic",
        "domain": "lakeside.example.edu",
    },
)

DEPARTMENTS = (
    {"name": "Computer Science", "code": "CS"},
    {"name": "Electrical Engineering", "code": "EE"},
)

FACULTY_NAMES = (
    "Avery Bennett", "Jordan Chen", "Morgan Patel", "Riley Thompson",
    "Casey Rivera", "Taylor Brooks", "Cameron Reed", "Quinn Foster",
    "Drew Sullivan", "Skyler James",
)

STUDENT_NAMES = (
    "Alex Morgan", "Sam Taylor", "Jamie Parker", "Robin Lee", "Charlie Davis",
    "Emerson Clark", "Kendall Lewis", "Finley Walker", "Reese Hall", "Dakota Young",
    "Harper Allen", "Rowan King", "Peyton Wright", "Sage Scott", "Blake Green",
    "Ari Adams", "Elliot Baker", "Remy Nelson", "Shiloh Carter", "Micah Mitchell",
    "Noel Perez", "Frankie Roberts", "Marley Turner", "Jules Phillips", "Lennon Campbell",
    "Cory Parker", "Ash Morgan", "Rory Edwards", "Ellis Collins", "River Stewart",
    "Kit Morris", "Oakley Rogers", "Milan Cook", "Indigo Bailey", "Wren Murphy",
    "Sasha Bell", "Toby Cooper", "Alden Richardson", "Mackenzie Cox", "Lane Howard",
    "Dylan Ward", "Avery Torres", "Bailey Peterson", "Cedar Gray", "Shawn Ramirez",
    "Logan James", "Jesse Watson", "Phoenix Brooks", "Cameron Kelly", "Tatum Sanders",
)


def require_schema(metadata):
    expected = {
        "colleges": {"id", "name", "slug", "domain"},
        "departments": {"id", "college_id", "name", "code"},
        "users": {
            "id", "college_id", "department_id", "email", "password_hash",
            "full_name", "role",
        },
    }
    missing_tables = sorted(set(expected) - set(metadata.tables))
    if missing_tables:
        raise RuntimeError(
            "Required existing tables were not found: " + ", ".join(missing_tables)
        )

    for table_name, required_columns in expected.items():
        actual_columns = set(metadata.tables[table_name].c.keys())
        missing_columns = sorted(required_columns - actual_columns)
        if missing_columns:
            raise RuntimeError(
                f"Table '{table_name}' is missing required columns: "
                + ", ".join(missing_columns)
            )


def get_existing_id(connection, table, filters):
    statement = select(table.c.id).where(
        *(table.c[column] == value for column, value in filters.items())
    )
    return connection.execute(statement).scalar_one_or_none()


def insert_record(connection, table, values):
    record = {key: value for key, value in values.items() if key in table.c}
    record["id"] = uuid.uuid4()

    missing_required = [
        column.name
        for column in table.columns
        if column.name not in record
        and not column.nullable
        and column.default is None
        and column.server_default is None
        and not column.autoincrement
        and not column.primary_key
    ]
    if missing_required:
        raise RuntimeError(
            f"Cannot seed '{table.name}'; required columns have no values or "
            "database defaults: " + ", ".join(missing_required)
        )

    connection.execute(table.insert().values(**record))
    return record["id"]


def get_or_create_college(connection, table, values, counts):
    existing_id = get_existing_id(connection, table, {"slug": values["slug"]})
    if existing_id is not None:
        existing_name = connection.execute(
            select(table.c.name).where(table.c.id == existing_id)
        ).scalar_one()
        if existing_name != values["name"]:
            raise RuntimeError(
                f"College slug '{values['slug']}' already belongs to a different name."
            )
        counts["colleges_reused"] += 1
        return existing_id

    counts["colleges_created"] += 1
    return insert_record(
        connection,
        table,
        {
            **values,
            "subscription_tier": "standard",
            "status": "active",
        },
    )


def get_or_create_department(connection, table, college_id, values, counts):
    existing_id = get_existing_id(
        connection,
        table,
        {"college_id": college_id, "code": values["code"]},
    )
    if existing_id is not None:
        existing_name = connection.execute(
            select(table.c.name).where(table.c.id == existing_id)
        ).scalar_one()
        if existing_name != values["name"]:
            raise RuntimeError(
                f"Department code '{values['code']}' already has a different name "
                f"in college {college_id}."
            )
        counts["departments_reused"] += 1
        return existing_id

    counts["departments_created"] += 1
    return insert_record(
        connection,
        table,
        {"college_id": college_id, **values},
    )


def get_or_create_user(connection, table, college_id, department_id, email, name, role, counts):
    existing_id = get_existing_id(
        connection,
        table,
        {"college_id": college_id, "email": email},
    )
    if existing_id is not None:
        existing = connection.execute(
            select(table.c.full_name, table.c.role, table.c.department_id).where(
                table.c.id == existing_id
            )
        ).one()
        if (existing.full_name, existing.role, existing.department_id) != (
            name,
            role,
            department_id,
        ):
            raise RuntimeError(
                f"Seed email '{email}' already exists with different user data; "
                "no existing data was changed."
            )
        counts[f"{role.lower()}_reused"] += 1
        return existing_id

    counts[f"{role.lower()}_created"] += 1
    return insert_record(
        connection,
        table,
        {
            "college_id": college_id,
            "department_id": department_id,
            "email": email,
            "password_hash": PASSWORD_HASH,
            "full_name": name,
            "role": role,
            "status": "active",
        },
    )


def seed_database():
    engine = create_engine(DATABASE_URL, pool_pre_ping=True)
    try:
        metadata = MetaData()
        metadata.reflect(
            bind=engine,
            only=["colleges", "departments", "users"],
        )
        require_schema(metadata)

        colleges = metadata.tables["colleges"]
        departments = metadata.tables["departments"]
        users = metadata.tables["users"]
        counts = {
            f"{entity}_{action}": 0
            for entity in ("colleges", "departments", "admin", "faculty", "student")
            for action in ("created", "reused")
        }

        with engine.begin() as connection:
            college_ids = []
            department_ids = []
            for college in COLLEGES:
                college_id = get_or_create_college(connection, colleges, college, counts)
                college_ids.append(college_id)
                department_ids.append(
                    [
                        get_or_create_department(
                            connection,
                            departments,
                            college_id,
                            department,
                            counts,
                        )
                        for department in DEPARTMENTS
                    ]
                )

            for college_index, college in enumerate(COLLEGES):
                college_id = college_ids[college_index]
                college_departments = department_ids[college_index]
                domain = college["domain"]

                get_or_create_user(
                    connection,
                    users,
                    college_id,
                    None,
                    f"admin@{domain}",
                    f"{college['name']} Administrator",
                    "ADMIN",
                    counts,
                )

                for faculty_index in range(5):
                    name = FACULTY_NAMES[college_index * 5 + faculty_index]
                    department_id = college_departments[faculty_index % 2]
                    get_or_create_user(
                        connection,
                        users,
                        college_id,
                        department_id,
                        f"faculty{faculty_index + 1:02d}@{domain}",
                        name,
                        "FACULTY",
                        counts,
                    )

                for student_index in range(25):
                    name = STUDENT_NAMES[college_index * 25 + student_index]
                    department_id = college_departments[student_index % 2]
                    get_or_create_user(
                        connection,
                        users,
                        college_id,
                        department_id,
                        f"student{student_index + 1:02d}@{domain}",
                        name,
                        "STUDENT",
                        counts,
                    )

        print("Database seeding completed.")
        for entity in ("colleges", "departments", "admin", "faculty", "student"):
            print(
                f"  {entity}: {counts[f'{entity}_created']} created, "
                f"{counts[f'{entity}_reused']} already present"
            )
        if PASSWORD_HASH == "!seeded-account-no-login!":
            print(
                "  Accounts use a non-login placeholder. Set SEED_PASSWORD_HASH to "
                "an application-generated hash if the accounts need to authenticate."
            )
    finally:
        engine.dispose()


if __name__ == "__main__":
    try:
        seed_database()
    except SQLAlchemyError as exc:
        print(
            "Database connection or seeding failed. Confirm PostgreSQL is running "
            "on localhost:5432 and DATABASE_URL/credentials are correct. "
            f"Details: {exc}",
            file=sys.stderr,
        )
        raise SystemExit(1) from exc
    except ModuleNotFoundError as exc:
        print(f"ACTUAL MODULE ERROR: {exc}", file=sys.stderr)

        raise SystemExit(1) from exc
    except RuntimeError as exc:
        print(f"Database schema or seed conflict: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc